added more files, and finilized the project structure for now.

diff --git a/Transportation System/Dockerfile b/Transportation System/Dockerfile
--- a/Transportation System/Dockerfile
+++ b/Transportation System/Dockerfile
@@ -7,9 +7,12 @@ EXPOSE 8081
 FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
 ARG BUILD_CONFIGURATION=Release
 WORKDIR /src
+
 COPY ["Transportation System/Transportation System.csproj", "Transportation System/"]
 RUN dotnet restore "Transportation System/Transportation System.csproj"
+
 COPY . .
+
 WORKDIR "/src/Transportation System"
 RUN dotnet build "./Transportation System.csproj" -c $BUILD_CONFIGURATION -o /app/build
 
@@ -20,4 +23,7 @@ RUN dotnet publish "./Transportation System.csproj" -c $BUILD_CONFIGURATION -o /
 FROM base AS final
 WORKDIR /app
 COPY --from=publish /app/publish .
+
+RUN ls -la /app/wwwroot/js/ || echo "wwwroot/js not found"
+
 ENTRYPOINT ["dotnet", "Transportation_System.dll"]
